//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterfaceWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consists_of
    {
        public int Id_Consists_of { get; set; }
        public int QuestionId_Question { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Question Question { get; set; }
    }
}
