//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterfaceWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int Id_Mark { get; set; }
        public string Description_of_mark { get; set; }
        public int Value_of_Mark { get; set; }
    
        public virtual Takes Take { get; set; }
    }
}
