//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterfaceWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teaching_topic
    {
        public int Id_Teaching_topic { get; set; }
        public string Topic_name { get; set; }
        public int Serial_number { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
